Repository Legal-Questioner/legal-questioner, pull requests merged in 2024-02, with the labels that each got.

#1 Add docker compose database and fix bug in db runner
  docker-compose.yml
  legalquestionizer/gradlew
  legalquestionizer/src/main/java/io/shaded/legalquestionizer/runner/DatabaseInitializerRunner.java
Labels: bug, good first issue

#2 Added null check and fixed tsquery call
  legalquestionizer/src/main/java/io/shaded/legalquestionizer/search/SearchController.java
  legalquestionizer/src/main/java/io/shaded/legalquestionizer/search/SearchService.java
Labels: bug

#3 Created react app with all frontend UI features
  legal-frontend/.gitignore
  legal-frontend/README.md
  legal-frontend/package-lock.json
  legal-frontend/package.json
  legal-frontend/public/LegalLogo.svg
  legal-frontend/public/index.html
  legal-frontend/public/manifest.json
  legal-frontend/public/robots.txt
  legal-frontend/src/App.css
  legal-frontend/src/App.js
  legal-frontend/src/App.test.js
  legal-frontend/src/components/AboutSection.js
  legal-frontend/src/components/NavBar.js
  legal-frontend/src/components/SearchBar.js
  legal-frontend/src/images/HomeDesign.svg
  legal-frontend/src/images/LegalLogo.svg
  legal-frontend/src/index.css
  legal-frontend/src/index.js
  legal-frontend/src/reportWebVitals.js
  legal-frontend/src/setupTests.js
  legal-frontend/tailwind.config.js
  legalquestionizer/src/main/java/io/shaded/legalquestionizer/search/SearchController.java
Labels: enhancement

#4 Implement gemini api
  README.md
  legalquestionizer/.gitignore
  legalquestionizer/build.gradle.kts
  legalquestionizer/src/main/java/io/shaded/legalquestionizer/context/ContextController.java
  legalquestionizer/src/main/java/io/shaded/legalquestionizer/context/ContextRequest.java
  legalquestionizer/src/main/java/io/shaded/legalquestionizer/context/ContextResponse.java
  legalquestionizer/src/main/java/io/shaded/legalquestionizer/context/ContextService.java
  legalquestionizer/src/main/java/io/shaded/legalquestionizer/context/ContextStrategy.java
  legalquestionizer/src/main/java/io/shaded/legalquestionizer/context/GoogleGeminiContextStrategy.java
  legalquestionizer/src/main/java/io/shaded/legalquestionizer/documents/Document.java
  legalquestionizer/src/main/java/io/shaded/legalquestionizer/documents/DocumentController.java
  legalquestionizer/src/main/java/io/shaded/legalquestionizer/documents/DocumentCreateRequest.java
  legalquestionizer/src/main/java/io/shaded/legalquestionizer/documents/DocumentService.java
  legalquestionizer/src/main/java/io/shaded/legalquestionizer/runner/DatabaseInitializerRunner.java
  legalquestionizer/src/main/java/io/shaded/legalquestionizer/search/SearchController.java
  legalquestionizer/src/main/java/io/shaded/legalquestionizer/search/SearchResponse.java
  legalquestionizer/src/main/java/io/shaded/legalquestionizer/search/SearchService.java
Labels: bug, enhancement

#5 Update README to contain more documentation
  README.md
Labels: documentation
